/** Column definitions for reports rendered via ReportPageShell + GenericReportTable */

export const REPORT_COLUMNS = {
  'teacher-performance': [
    { key: 'teacherName', label: 'Teacher Name' },
    { key: 'studioName', label: 'Studio' },
    { key: 'totalLessons', label: 'Total Lessons' },
    { key: 'activeStudents', label: 'Active Students' },
    { key: 'revenueGenerated', label: 'Revenue Generated' },
    { key: 'introConversions', label: 'Intro Conversions' },
    { key: 'programUpgrades', label: 'Program Upgrades' },
    { key: 'retentionPct', label: 'Retention %' },
    { key: 'avgLessonsPerStudent', label: 'Avg Lessons per Student' },
  ],
  'teacher-lesson-count': [
    { key: 'teacherName', label: 'Teacher Name' },
    { key: 'studioName', label: 'Studio' },
    { key: 'completedLessons', label: 'Completed' },
    { key: 'cancelledLessons', label: 'Cancelled' },
    { key: 'noShowLessons', label: 'No-Shows' },
    { key: 'complimentaryLessons', label: 'Complimentary' },
    { key: 'totalLessons', label: 'Total Lessons' },
  ],
  'intro-conversion': [
    { key: 'leadName', label: 'Lead / Student' },
    { key: 'teacherName', label: 'Teacher' },
    { key: 'studioName', label: 'Studio' },
    { key: 'introDate', label: 'Intro Date' },
    { key: 'showed', label: 'Showed' },
    { key: 'converted', label: 'Converted' },
    { key: 'programSold', label: 'Program Sold' },
    { key: 'saleAmount', label: 'Sale Amount' },
    { key: 'timeToConvert', label: 'Time to Convert' },
    { key: 'leadSource', label: 'Lead Source' },
  ],
  'lead-source-performance': [
    { key: 'leadSource', label: 'Lead Source' },
    { key: 'leadsCreated', label: 'Leads Created' },
    { key: 'booked', label: 'Booked' },
    { key: 'showed', label: 'Showed' },
    { key: 'sold', label: 'Sold' },
    { key: 'conversionPct', label: 'Conversion %' },
    { key: 'totalSales', label: 'Total Sales' },
    { key: 'cashCollected', label: 'Cash Collected' },
    { key: 'avgSaleAmount', label: 'Avg Sale Amount' },
  ],
  'program-progression': [
    { key: 'studentName', label: 'Student Name' },
    { key: 'teacherName', label: 'Teacher' },
    { key: 'firstProgramType', label: 'First Program Type' },
    { key: 'secondProgramType', label: 'Second Program Type' },
    { key: 'thirdProgramType', label: 'Third Program Type' },
    { key: 'firstPurchaseDate', label: 'First Purchase Date' },
    { key: 'secondPurchaseDate', label: 'Second Purchase Date' },
    { key: 'thirdPurchaseDate', label: 'Third Purchase Date' },
    { key: 'totalSpend', label: 'Total Spend' },
    { key: 'timeBetweenPurchases', label: 'Time Between Purchases' },
  ],
  'purchase-progression': [
    { key: 'studentName', label: 'Student Name' },
    { key: 'teacherName', label: 'Teacher' },
    { key: 'firstPurchaseType', label: 'First Purchase Type' },
    { key: 'secondPurchaseType', label: 'Second Purchase Type' },
    { key: 'thirdPurchaseType', label: 'Third Purchase Type' },
    { key: 'fourthPurchaseType', label: 'Fourth Purchase Type' },
    { key: 'firstPurchaseDate', label: 'First Purchase Date' },
    { key: 'secondPurchaseDate', label: 'Second Purchase Date' },
    { key: 'thirdPurchaseDate', label: 'Third Purchase Date' },
    { key: 'fourthPurchaseDate', label: 'Fourth Purchase Date' },
    { key: 'totalSpend', label: 'Total Spend' },
    { key: 'timeBetweenPurchases', label: 'Time Between Purchases' },
  ],
  'student-retention': [
    { key: 'studentName', label: 'Student Name' },
    { key: 'teacherName', label: 'Teacher' },
    { key: 'studioName', label: 'Studio' },
    { key: 'firstLessonDate', label: 'First Lesson Date' },
    { key: 'lastLessonDate', label: 'Last Lesson Date' },
    { key: 'lessonsTaken', label: 'Lessons Taken' },
    { key: 'status', label: 'Status' },
    { key: 'daysSinceLastLesson', label: 'Days Since Last Lesson' },
    { key: 'retained', label: 'Retained' },
    { key: 'totalSpend', label: 'Total Spend' },
  ],
  'revenue-by-program': [
    { key: 'programName', label: 'Program / Product' },
    { key: 'programType', label: 'Program Type' },
    { key: 'studioName', label: 'Studio' },
    { key: 'sales', label: 'Sales' },
    { key: 'cashCollected', label: 'Cash Collected' },
    { key: 'studentCount', label: 'Student Count' },
    { key: 'avgSaleAmount', label: 'Avg Sale Amount' },
  ],
  'package-utilization': [
    { key: 'studentName', label: 'Student Name' },
    { key: 'teacherName', label: 'Teacher' },
    { key: 'studioName', label: 'Studio' },
    { key: 'packageName', label: 'Package / Program' },
    { key: 'lessonsPurchased', label: 'Lessons Purchased' },
    { key: 'lessonsUsed', label: 'Lessons Used' },
    { key: 'lessonsRemaining', label: 'Lessons Remaining' },
    { key: 'utilizationPct', label: 'Utilization %' },
    { key: 'purchaseDate', label: 'Purchase Date' },
  ],
  growth: [
    { key: 'metric', label: 'Metric' },
    { key: 'currentPeriod', label: 'Current Period' },
    { key: 'priorPeriod', label: 'Prior Period' },
    { key: 'change', label: 'Change' },
    { key: 'changePct', label: 'Change %' },
  ],
  'studio-comparison': [
    { key: 'studioName', label: 'Studio' },
    { key: 'sales', label: 'Sales' },
    { key: 'cashCollected', label: 'Cash Collected' },
    { key: 'activeStudents', label: 'Active Students' },
    { key: 'newLeads', label: 'New Leads' },
    { key: 'conversionPct', label: 'Conversion %' },
    { key: 'revenuePerStudent', label: 'Revenue per Student' },
    { key: 'lessonsCompleted', label: 'Lessons Completed' },
  ],
}

export function getReportColumns(slug) {
  return REPORT_COLUMNS[slug] || []
}
